config/routes.rb
Rails.application.routes.draw do
  resources :notes
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @show_note = Note.find(params[:id])
  end

  def new
    @new_note = Note.new
  end

  def create
    @new_note = Note.new(params.require(:note).permit(:title, :due, :body))

    if @new_note.save
      redirect_to notes_path
    else 
      renders :new
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(params.require(:note).permit(:title, :due, :body))
      redirect_to notes_path
    else
      renders :edit
    end
  end
  
  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1> Edit Your Note </h1>

<%= form_for @note do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>

  <%= f.label :due %>
  <%= f.date_field :due %>
  
  <%= f.label :body  %>
  <%= f.text_area :body %>

  <%= f.submit %>

  <%= link_to  "Back", notes_path %>
  
<% end %>

app/views/notes/index.html.erb
<h1> Notes </h1>

 <%= link_to  "New Note", new_note_path %>
<% @notes.each do |note| %>
  <h2> <%= note.title  %></h2>
  <%= link_to 'View Note', note_path(note)  %>
  <%= link_to 'Edit Note', edit_note_path(note) %>
  <%= link_to  "Delete Note", note_path(note), method: :delete %>
<% end %>

app/views/notes/new.html.erb
<h1>Notes#new</h1>
<p>Find me in app/views/notes/new.html.erb</p>

app/views/notes/show.html.erb
<h1><%= @show_note.title %></h1>
<h4> <%= @show_note.due %></h4>
<p><%= @show_note.body %> </p>
<%= link_to 'Back', notes_path %>